apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-app-dev
  namespace: argocd
  labels:
    app.kubernetes.io/instance: case
spec:
  project: default
  source:
    repoURL: https://github.com/peddepri/case
    targetRevision: HEAD
    path: domains/platform/helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: case
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/instance: case
spec:
  project: default
  source:
    repoURL: https://github.com/peddepri/case
    targetRevision: HEAD
    path: domains/platform/helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: case-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true