{{- if .Values.mobile.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
  labels:
    app: mobile
spec:
  replicas: {{ .Values.mobile.replicaCount }}
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
        - name: mobile
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.mobile.image.repository }}:{{ .Values.mobile.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 19006
          resources:
            requests:
              cpu: {{ .Values.mobile.resources.requests.cpu | quote }}
              memory: {{ .Values.mobile.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mobile.resources.limits.cpu | quote }}
              memory: {{ .Values.mobile.resources.limits.memory | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: mobile
  labels:
    app: mobile
spec:
  type: ClusterIP
  selector:
    app: mobile
  ports:
    - name: http
      port: 19006
      targetPort: 19006
{{- if .Values.mobile.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mobile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mobile
  minReplicas: {{ .Values.mobile.hpa.minReplicas }}
  maxReplicas: {{ .Values.mobile.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mobile.hpa.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.mobile.hpa.memoryAverageUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}
{{- end }}
