# Dev environment overrides
global:
  imageRegistry: "918859180133.dkr.ecr.us-east-1.amazonaws.com"
  ingressHost: case.local

backend:
  image:
    tag: latest
  hpa:
    enabled: false   # disable HPA in dev quick test
  service:
    enabled: false    # keep disabled until ALB webhook is installed/fixed

frontend:
  image:
    tag: latest
  hpa:
    enabled: false
  service:
    enabled: false

mobile:
  image:
    tag: latest
  hpa:
    enabled: false
  service:
    enabled: false

ingress:
  enabled: false  # disable ingress while testing basic pod readiness

adot:
  enabled: false
  metricsNamespace: case-dev
