# Dev environment overrides
global:
  imageRegistry: "918859180133.dkr.ecr.us-east-1.amazonaws.com"
  ingressHost: case.local

backend:
  image:
    tag: latest
  hpa:
    enabled: false   # disable HPA in dev quick test
  service:
    enabled: true     # enable Service in dev

frontend:
  image:
    tag: latest
  hpa:
    enabled: false
  service:
    enabled: true

mobile:
  image:
    tag: latest
  hpa:
    enabled: false
  service:
    enabled: true

ingress:
  enabled: true   # enable ingress (ALB)

adot:
  enabled: false
  metricsNamespace: case-dev
